[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = "v.weight = G.P_CENTERS[v.name]:get_weight()   -- Apply game modifiers where appropriate (defined in edition declaration)"
position = "after"
payload = """if v.name == "e_polychrome" then
    for _, card in pairs(SMODS.find_card("j_mf_aheartofcold")) do
        v.weight = v.weight * card.ability.extra.polychrome_mod
    end
end"""
match_indent = true