[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '-- TARGET: adding to hand effects'
position = 'before'
payload = '''
if G.GAME.rot_trib_count then
    local mf_add_cards = {}
    for i = 1, G.GAME.rot_trib_count do
        mf_add_cards[#mf_add_cards + 1] = SMODS.add_card {
            area = G.discard,
            set = "Base",
            rank = "K",
        }
        mf_add_cards[#mf_add_cards + 1] = SMODS.add_card {
            area = G.discard,
            set = "Base",
            rank = "Q",
        }
    end
    for i,v in ipairs(mf_add_cards) do
		table.insert(final_scoring_hand,v)
		v.area:remove_card(v)
		G.play:emplace(v)
        v.mf_royal_decreed = true
    end
end
'''
match_indent = true
